site_name: IT358 Honeypot Lab
site_url: https://ckrez.github.io/it358-chn/
theme: readthedocs
docs_dir: docs
markdown_extensions:
- markdown.extensions.admonition
pages:
    - 'Using SSH': index.md
    - 'Prepare your hosts': preparing.md
    - 'Building CHN Server': build_server.md
    - 'Deploying Your First Honeypot': first_honeypot.md
    - 'Setting Up Logging for Honeypot Data': configuring_logging.md
    - 'Setting Up Logging to CIFv3': configuring_cif.md
    - 'Exploring your data in CIFv3': exploring_cif.md
    - 'Exploring your data in Kibana': exploring_kibana.md
